### ISSUE TITLE
Can't include web3c.js in truffle-deployer

### ISSUE THREAD

**Issue by armaniferrante** [oasislabs/web3c.js#132]
After adding web3c.js to https://github.com/oasislabs/truffle/blob/ekiden/packages/truffle-deployer/index.js and building truffle, I get the following error when running `truffle migrate`.

```
ReferenceError: window is not defined
    at Object.subtle (/oasislabs/truffle/packages/truffle/build/webpack:/~/web3c/crypto/subtle/mrae_box.js:3:1)
    at __webpack_require__ (/oasislabs/truffle/packages/truffle/build/webpack:/webpack/bootstrap 2b72c841b84a369f0900:19:1)
    at Object.<anonymous> (/oasislabs/truffle/packages/truffle/build/webpack:/~/web3c/web3c/index.js:2:17)
    at __webpack_require__ (/oasislabs/truffle/packages/truffle/build/webpack:/webpack/bootstrap 2b72c841b84a369f0900:19:1)
    at Object.<anonymous> (/oasislabs/truffle/packages/truffle/build/webpack:/~/web3c/index.browser.js:2:13)
    at __webpack_require__ (/oasislabs/truffle/packages/truffle/build/webpack:/webpack/bootstrap 2b72c841b84a369f0900:19:1)
    at Object.module.exports (/oasislabs/truffle/packages/truffle/build/webpack:/packages/truffle-deployer/index.js:7:15)
    at __webpack_require__ (/oasislabs/truffle/packages/truffle/build/webpack:/webpack/bootstrap 2b72c841b84a369f0900:19:1)
    at Object.<anonymous> (/oasislabs/truffle/packages/truffle/build/webpack:/packages/truffle-migrate/migration.js:2:18)
    at __webpack_require__ (/oasislabs/truffle/packages/truffle/build/webpack:/webpack/bootstrap 2b72c841b84a369f0900:19:1)
    at Object.<anonymous> (/oasislabs/truffle/packages/truffle/build/webpack:/packages/truffle-migrate/index.js:7:19)
    at __webpack_require__ (/oasislabs/truffle/packages/truffle/build/webpack:/webpack/bootstrap 2b72c841b84a369f0900:19:1)
    at Object.run (/oasislabs/truffle/packages/truffle/build/webpack:/packages/truffle-core/lib/commands/migrate.js:62:19)
    at Command.run (/oasislabs/truffle/packages/truffle/build/webpack:/packages/truffle-core/lib/command.js:113:1)
    at Object.<anonymous> (/oasislabs/truffle/packages/truffle/build/webpack:/packages/truffle-core/cli.js:47:1)
    at __webpack_require__ (/oasislabs/truffle/packages/truffle/build/webpack:/webpack/bootstrap 2b72c841b84a369f0900:19:1)
    at /oasislabs/truffle/packages/truffle/build/webpack:/webpack/bootstrap 2b72c841b84a369f0900:65:1
    at Object.<anonymous> (/oasislabs/truffle/packages/truffle/build/cli.bundled.js:71:10)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
Truffle v5.0.2 (core: 5.0.0)
Node v8.15.0
```

**Comment by willscott** [comment]
looks like it's taking the web browser crypto path rather than the node one.

**Comment by willscott** [comment]
we default to node, but our web pack config aliases to browser: https://github.com/oasislabs/web3c.js/blob/master/webpack.config.js#L33

so if you webpack it, you get the browser one.

**Comment by armaniferrante** [comment]
Done. Closing.
